---
- name: change keyboard layout to de
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT='
    line: 'XKBLAYOUT="de"'
  register: lang

- name: apply keyboard layout
  ansible.builtin.command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
  when: lang.changed

- name: apply keyboard layout
  ansible.builtin.systemd:
    name: keyboard-setup
    state: restarted
  when: lang.changed

# - name: remove cdrom from apt sources
#   lineinfile:
#     path: /etc/apt/sources.list
#     regexp: '^deb cdrom:'
#     state: absent

- name: install services
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    force: yes
    update_cache: yes
  vars:
    packages:
      # - open-vm-tools
      - htop
      - vim
      - git
      # - net-tools

- name: dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'

- name: modify hosts file
  ansible.builtin.template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: change hostname
  ansible.builtin.hostname:
    name: "{{hostname|default(lookup('community.general.random_pet', words=2, prefix='lorabridge' if 'bridges' in group_names else 'loragateway')) }}"

- name: disable usb autosuspend
  block:
    - name: disable usb autosuspend for current boot
      ansible.builtin.shell: "echo -1 > /sys/module/usbcore/parameters/autosuspend"
    - name: disable usb autosuspend permanently
      ansible.builtin.shell: "echo $(cat /boot/cmdline.txt | python3 -c 'import sys;print(sys.stdin.read().strip())') usbcore.autosuspend=-1 > /boot/cmdline.txt"